version: '2'
services:
  web:
    container_name: dockerflask
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
